ElectoralSystem/Controllers/CandidatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectoralSystem.Controllers
{
    public class CandidatesController : Controller
    {
        // GET: CandidatesMap
        public ActionResult Map()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }
    }
}

ElectoralSystem/Controllers/ElectoralChartsController.cs
using System.Web.Mvc;
using ElectoralSystem.ElectoralDbAcces;
using System.Data;
using Newtonsoft.Json;

namespace ElectoralSystem.Controllers
{
    public class ElectoralChartsController : Controller
    {
        ElectoralDbAccess db;
        // GET: ElectoralCharts
        public ActionResult Index()
        {
            return View();
        }

        public ContentResult GetCandidatesList(string codeMap)
        {
            string[] codeMaps = codeMap.Split('-');
            db = new ElectoralDbAccess();

            DataTable dt = db.GetCandidatesList(codeMaps[1]);
                  
            return Content(JsonConvert.SerializeObject(dt), "json/application");
        }
    }
}

ElectoralSystem/Controllers/HomeController.cs
using ElectoralSystem.ElectoralDbAcces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ElectoralSystem.Controllers
{
    public class HomeController : Controller
    {
        ElectoralDbAccess db;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ElectoralSystem/Controllers/IncidentsReportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectoralSystem.Controllers
{
    public class IncidentsReportController : Controller
    {
        // GET: IncidentsReport
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload()
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images/uploads"), fileName);
                    file.SaveAs(path);
                }
            }

            return RedirectToAction("UploadDocument");
        }
    }
}

ElectoralSystem/Controllers/InstructivoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectoralSystem.Controllers
{
    public class InstructivoController : Controller
    {
        // GET: Instructivo
        public ActionResult Index()
        {
            return View();
        }
    }
}

ElectoralSystem/Views/Candidates/Map.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles{

<link href="@Url.Content("~/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css")" rel="stylesheet" />


    <style type="text/css">
        #mapCandidates {
            height: 500px;
            min-width: 310px;
            max-width: 100%;
            margin: 0 auto;
        }

        .loading {
            margin-top: 10em;
            text-align: center;
            color: gray;
        }
    </style>
}


<div class="boxed">

    <!--CONTENT CONTAINER-->
    <!--===================================================-->
    <div id="content-container">

        <!--Page Title-->
        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        @*<div id="page-title">
                <h1 class="page-header text-overflow">Lista de Distribución</h1>


            </div>*@
        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <!--End page title-->
        <!--Page content-->
        <!--===================================================-->
        <div id="page-content">

            <div class="row">
                <div class="col-sm-12">
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">B&uacute;squeda de candidatos por Zona</h3>
                        </div>

                        <!--Hover Rows-->
                        <!--===================================================-->
                        <div class="panel-body">
                            <div id="mapCandidates">
                                
                            </div>
                        </div>

                    </div>
                </div>
      

                        <div class="col-sm-12">
                            <section id="candidatesList" style="display:none">
                                @Html.Partial("_CandidatesList")
                            </section>

                        </div>
                    </div>
                </div>
    </div>

</div>


@section scripts{

 <script src="https://code.highcharts.com/maps/highmaps.js"></script>
<script src="https://code.highcharts.com/maps/modules/data.js"></script>
<script src="https://code.highcharts.com/maps/modules/drilldown.js"></script>
<script src="https://code.highcharts.com/mapdata/countries/do/do-all.js"></script>


<script src="@Url.Content("~/plugins/datatables/media/js/jquery.dataTables.js")"></script>
<script src="@Url.Content("~/plugins/datatables/media/js/dataTables.bootstrap.js")"></script>
<script src="@Url.Content("~/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js")"></script>

    <script src="@Url.Content("~/Scripts/Electoral/Map.js")"></script>
}

ElectoralSystem/Views/Candidates/_CandidatesList.cshtml
   <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Lista de Candidatos</h3>
            </div>

            <!--Hover Rows-->
            <!--===================================================-->
            <div class="panel-body">
                <table id="tbCandidatesList" data-url="@Url.Action("GetCandidatesList", "ElectoralCharts")" class="table table-hover table-vcenter">
                    <thead>
                        <tr>
                            <th class="min-width"></th>
                            <th>Nombre</th>
                            <th class="text-center">Nivel Cargo</th>
                            <th class="text-center">Provincia</th>
                            <th class="text-center">Partido</th>
                        </tr>
                    </thead>
                    <tbody>
                        @*<tr>
                            <td class="text-center"><img src="@Url.Content("~/img/av2.png")" class="img-circle img-sm" /></td>
                            <td>
                                <span class="text-semibold">Juan Padilla</span>
                                <br>
                                <small class="text-muted">ALCALDE</small>
                            </td>
                            <td class="text-center"><span class="text-semibold">Consuelo</span></td>
                            <td class="text-center"><span class="ext-semibold">PRD</span></td>
                        </tr>
                        <tr>
                            <td class="text-center"><img src="@Url.Content("~/img/av3.png")" class="img-circle img-sm" /></td>
                            <td>
                                <span class="text-semibold">Dioris Mota</span>
                                <br>
                                <small class="text-muted">VICEALCALDE</small>
                            </td>
                            <td class="text-center"><span class="text-semibold">Consuelo</span></td>
                            <td class="text-center"><span class="text-semibold">PRD</span></td>
                        </tr>
                        <tr>
                            <td class="text-center"><img src="@Url.Content("~/img/av1.png")" class="img-circle img-sm" /></td>
                            <td>
                                <span class="text-semibold">Juan Carrasco</span>
                                <br>
                                <small class="text-muted">REGIDOR</small>
                            </td>
                            <td class="text-center"><span class="text-semibold">Consuelo</span></td>
                            <td class="text-center"><span class="text-semibold">PRD</span></td>
                        </tr>
                        <tr>
                            <td class="text-center"><img src="@Url.Content("~/img/av4.png")" class="img-circle img-sm" /></td>
                            <td>
                                <span class="text-semibold">Cristina De La Cruz</span>
                                <br>
                                <small class="text-muted">REGIDOR</small>
                            </td>
                            <td class="text-center"><span class="text-semibold">Consuelo</span></td>
                            <td class="text-center"><span class="text-semibold">PRD</span></td>
                        </tr>
                        <tr>
                            <td class="text-center"><img src="@Url.Content("~/img/av2.png")" class="img-circle img-sm" /></td>
                            <td>
                                <span class="text-semibold">Juan Padilla</span>
                                <br>
                                <small class="text-muted">ALCALDE</small>
                            </td>
                            <td class="text-center"><span class="text-semibold">Consuelo</span></td>
                            <td class="text-center"><span class="text-semibold">PRD</span></td>
                        </tr>
                        <tr>
                            <td class="text-center"><img src="@Url.Content("~/img/av2.png")" class="img-circle img-sm" /></td>
                            <td>
                                <span class="text-semibold">Juan Padilla</span>
                                <br>
                                <small class="text-muted">ALCALDE</small>
                            </td>
                            <td class="text-center"><span class="text-semibold">Consuelo</span></td>
                            <td class="text-center"><span class="text-semibold">PRD</span></td>
                        </tr>*@
                    </tbody>
                </table>
            </div>
            <!--===================================================-->
            <!--End Hover Rows-->

        </div>

ElectoralSystem/Views/ElectoralCharts/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles{

    <style type="text/css">
        #mapCandidates {
            height: 500px;
            min-width: 310px;
            max-width: 100%;
            margin: 0 auto;
        }

        .loading {
            margin-top: 10em;
            text-align: center;
            color: gray;
        }
    </style>
}


<div class="boxed">

    <!--CONTENT CONTAINER-->
    <!--===================================================-->
    <div id="content-container">

        <div id="page-content">

            <div class="row">
                <div class="col-sm-12">
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">Proyecci&oacute;n población mayor de edad</h3>
                        </div>

                        <!--Hover Rows-->
                        <!--===================================================-->
                        <div class="panel-body">
                            <div id="totalVoters">

                            </div>
                        </div>

                    </div>
                </div>


            </div>

            <div class="row">
                <div class="col-sm-6">


                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">Proyecci&oacute;n población estimada ONE 2016</h3>
                        </div>

                        <!--Hover Rows-->
                        <!--===================================================-->
                        <div class="panel-body">

                            <div class="col-sm-8">
                                <div id="censusAdultPopulation"></div>

                            </div>
                            <div class="col-sm-4">
                                <table class="table table-hover table-vcenter">
                                    <thead>
                                        <tr>
                                            <th>Desc</th>
                                            <th>Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><span style="color:#FF5252; font-weight:600">Femenino</span></td>
                                            <td><span style="color:#FF5252; font-weight:600">3,323,670</span></td>
                                        </tr>
                                        <tr>
                                            <td><span style="color:#5aaedc; font-weight:600">Masculino</span></td>
                                            <td><span style="color:#5aaedc; font-weight:600">3,264,669</span></td>
                                        </tr>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td><span style="font-weight:600">Total:</span></td>
                                            <td><span style="font-weight:600">6,588,339</span></td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>

                        </div>

                    </div>

                </div>

                <div class="col-sm-6">
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">.</h3>
                        </div>

                        <!--Hover Rows-->
                        <!--===================================================-->
                        <div class="panel-body">
                            <div class="col-sm-8">
                                <div id="padronAdultPopulation"></div>
                            </div>
                                <div class="col-sm-4">
                                    <table class="table table-hover table-vcenter">
                                        <thead>
                                            <tr>
                                                <th>Desc</th>
                                                <th>Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td><span style="color:#FF5252; font-weight:600">Femenino</span></td>
                                                <td><span style="color:#FF5252; font-weight:600">3,439,354</span></td>
                                            </tr>
                                            <tr>
                                                <td><span style="color:#5aaedc; font-weight:600">Masculino</span></td>
                                                <td><span style="color:#5aaedc; font-weight:600">3,325,782</span></td>
                                            </tr>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <td><span style="font-weight:600">Total:</span></td>
                                                <td><span style="font-weight:600">6,765,136</span></td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>

                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">Contribuci&oacute;n Econ&oacute;mica Electoral</h3>
                        </div>

                        <!--Hover Rows-->
                        <!--===================================================-->
                        <div class="panel-body">
                            <div id="budget">
                            </div>
                        </div>

                    </div>
                </div>


            </div>
        </div>


    </div>

</div>


@section scripts{

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>

    <script src="@Url.Content("~/Scripts/Electoral/ElectoralCharts.js")"></script>
}

ElectoralSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ElectoralSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ElectoralSystem/Views/Instructivo/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--Page content-->
<!--===================================================-->
<div class="boxed">

    <!--CONTENT CONTAINER-->
    <!--===================================================-->
    <div id="content-container">
        <div id="page-content">

            <div class="row">
                <div class="col-lg-12">
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">Instructivo Votaci&oacute;n</h3>
                        </div>
                        <div class="panel-body">
                            <!-- Timeline -->
                            <!--===================================================-->
                            <div class="timeline">

                                <!-- Timeline header -->
                                <div class="timeline-header">
                                    <div class="timeline-header-title bg-info">Así Se Vota</div>
                                </div>

                                <div class="timeline-entry">
                                    <div class="timeline-stat">
                                        <div class="timeline-icon bg-danger">
                                            <i class="fa fa-building fa-lg"></i>
                                        </div>
                                        <div class="timeline-time">Paso 1</div>
                                    </div>
                                    <div class="timeline-label">
                                        <h4 class="mar-no pad-btm"><a href="#" class="text-danger">Acude a tu colegio electoral</a></h4>
                                        <p>Verifica el colegio que te corresponde en el dorso de tu cédula o <a href="#">consúltalo aquí.</a></p>
                                    </div>
                                    <div class="timeline-label">
                                        <p>Dirígete con tu cédula al colegio correspondiente. Los colegios estarán abiertos desde las 6:00 AM</p>
                                    </div>                                    
                                </div>

                                <div class="timeline-entry">
                                    <div class="timeline-stat">
                                        <div class="timeline-icon">
                                            <img alt="Profile picture" src="~/img/fingerprint.png">
                                        </div>
                                        <div class="timeline-time">Paso 2</div>
                                    </div>
                                    <div class="timeline-label">
                                        <h4 class="mar-no pad-btm"><a href="#" class="text-dark">Regístrate con tu huella digital</a></h4>
                                        <p>Ya en la mesa electoral, entrega tu cédula al secretario para que tus datos sean ingresados en el dispositivo de registro.</p>
                                    </div>
                                    <div class="timeline-label">
                                        <p>Tu registro será realizado mediante huella digital para verificar tu identidad.</p>
                                    </div>

                                </div>

                                <div class="timeline-entry">
                                    <div class="timeline-stat">
                                        <div class="timeline-icon bg-warning">
                                            <i class="fa fa-film fa-lg"></i>
                                        </div>
                                        <div class="timeline-time">Paso 3</div>
                                    </div>
                                    <div class="timeline-label">
                                        <h4 class="mar-no pad-btm"><a href="#" class="text-warning">Recibe la Boleta</a></h4>
                                        <p>Ya registrado recibirás 3 boletas firmadas y selladas. Si vives en el exterior, solo recibirás 2 boletas.</p>
                                    </div>

                                </div>
                            </div>

                            <div class="timeline-entry">
                                <div class="timeline-stat">
                                    <div class="timeline-icon bg-success">
                                        <i class="fa fa-check fa-lg"></i>
                                    </div>
                                    <div class="timeline-time">Paso 4</div>
                                </div>
                                <div class="timeline-label">
                                    <h4 class="mar-no pad-btm"><a href="#" class="text-success">Ejerce tu derecho y elige tus candidatos</a></h4>
                                    <p>Ya en la caseta de votación, marca cada boleta correctamente.</p>
                                </div>
                                <div class="timeline-label">
                                    <p>Dobla en cuatro tus boletas. Deposita cada una en su urna correspondiente.</p>
                                </div>

                            </div>
                            <!--===================================================-->
                            <!-- End Timeline -->
                        </div>
                    </div>
                </div>
            </div>
        </div>

        </div>
    </div>
        <!--===================================================-->
        <!--End page content-->